# Cache-ordered loop macros for spectral arrays.
#
# These macros are deliberately written out rather than generated by helper
# code.  Spectral loops are performance-critical, and the expanded loop order
# should be obvious at a glance.

"""
    @loop_rfft3_4d array expr

Loop over a 4D spectral array whose transformed dimensions are `(2, 3, 4)`.
Dimension 2 is the rfft dimension and stores non-negative wavenumbers only.
Dimensions 3 and 4 are ordinary FFT dimensions stored in FFTW signed order:

    0, 1, ..., N/2, -(N/2-1), ..., -1

The loop order is cache-friendly for Julia arrays: dimension 1 is innermost.
The signed dimensions are split into four positive/negative blocks, so the
loop body has no signed-wavenumber branch.

Inside `expr`, the macro defines:

- `_i1`, `_i2`, `_i3`, `_i4`: 1-based array indices.
- `_n2`, `_n3`, `_n4`: integer wavenumbers for dimensions 2, 3, and 4.

# Example

```julia
@loop_rfft3_4d u begin
    out[_i1, _i2, _i3, _i4] =
        (_n2^2 + _n3^2 + _n4^2) * u[_i1, _i2, _i3, _i4]
end
```
"""
macro loop_rfft3_4d(array, expr)
    arr = esc(array)
    body = esc(expr)

    quote
        # n3 >= 0, n4 >= 0
        for $(esc(:_i4)) in 1:(Base.size($arr, 4) >> 1) + 1
            $(esc(:_n4)) = $(esc(:_i4)) - 1
            for $(esc(:_i3)) in 1:(Base.size($arr, 3) >> 1) + 1
                $(esc(:_n3)) = $(esc(:_i3)) - 1
                for $(esc(:_i2)) in 1:Base.size($arr, 2)
                    $(esc(:_n2)) = $(esc(:_i2)) - 1
                    for $(esc(:_i1)) in 1:Base.size($arr, 1)
                        $body
                    end
                end
            end
        end

        # n3 < 0, n4 >= 0
        for $(esc(:_i4)) in 1:(Base.size($arr, 4) >> 1) + 1
            $(esc(:_n4)) = $(esc(:_i4)) - 1
            for $(esc(:_i3)) in (Base.size($arr, 3) >> 1) + 2:Base.size($arr, 3)
                $(esc(:_n3)) = $(esc(:_i3)) - Base.size($arr, 3) - 1
                for $(esc(:_i2)) in 1:Base.size($arr, 2)
                    $(esc(:_n2)) = $(esc(:_i2)) - 1
                    for $(esc(:_i1)) in 1:Base.size($arr, 1)
                        $body
                    end
                end
            end
        end

        # n3 >= 0, n4 < 0
        for $(esc(:_i4)) in (Base.size($arr, 4) >> 1) + 2:Base.size($arr, 4)
            $(esc(:_n4)) = $(esc(:_i4)) - Base.size($arr, 4) - 1
            for $(esc(:_i3)) in 1:(Base.size($arr, 3) >> 1) + 1
                $(esc(:_n3)) = $(esc(:_i3)) - 1
                for $(esc(:_i2)) in 1:Base.size($arr, 2)
                    $(esc(:_n2)) = $(esc(:_i2)) - 1
                    for $(esc(:_i1)) in 1:Base.size($arr, 1)
                        $body
                    end
                end
            end
        end

        # n3 < 0, n4 < 0
        for $(esc(:_i4)) in (Base.size($arr, 4) >> 1) + 2:Base.size($arr, 4)
            $(esc(:_n4)) = $(esc(:_i4)) - Base.size($arr, 4) - 1
            for $(esc(:_i3)) in (Base.size($arr, 3) >> 1) + 2:Base.size($arr, 3)
                $(esc(:_n3)) = $(esc(:_i3)) - Base.size($arr, 3) - 1
                for $(esc(:_i2)) in 1:Base.size($arr, 2)
                    $(esc(:_n2)) = $(esc(:_i2)) - 1
                    for $(esc(:_i1)) in 1:Base.size($arr, 1)
                        $body
                    end
                end
            end
        end

        nothing
    end
end
